services:
  db:
    image: postgres
    container_name: contenedor
    environment:
      POSTGRES_USER: felipe
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: usuariosdb
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    driver: local